server:
  port: 8092
  compression:
    enabled: true


spring:
  data:
    rest:
      detection-strategy: annotated
  datasource:
    url: jdbc:postgresql://127.0.0.1:5433/rashod_java_prod
    username: postgres
    password: p123
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
  liquibase:
    changeLog: classpath:/liquibase/db.changelog-master.xml
    drop-first: false

app:
  param:
    dictionaries:
      operationTypes:
        - key: CONSUMPTION
          value: Расход
        - key: INCOME
          value: Доход
        - key: TRANSFER
          value: Перевод
      accountTypes:
        - key: SIMPLE
          value: Простой
        - key: DEBT
          value: Долг
        - key: GOAL
          value: Цель
      currencies:
        - key: RUB
          value: Рубль
        - key: EURO
          value: Евро
        - key: DOLLAR
          value: Доллар
        - key: AURUM
          value: Золото
        - key: ARGENTUM
          value: Серебро
        - key: YANDEX
          value: Акции Яндекс
        - key: ETF_CH
          value: Акции Китайских компаний
        - key: LTC
          value: Lite Coin
        - key: XRP
          value: Ripple
        - key: NMC
          value: Name Coin
        - key: ZEC
          value: ZEC
        - key: XMR
          value: XMR
        - key: VTC
          value: VTC
      accountStatuses:
        - key: ACTIVE
          value: Активен
        - key: INACTIVE
          value: Архивный
      paramGroups:
        - key: COMMON
          value: Общие
        - key: PLAN
          value: План
      paramKeys:
        - key: SUM_TO_MONTH
          value: План на текущий месяц
