spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5433/rashod_java_prod
    username: postgres
    password: p123
  liquibase:
    drop-first: false
  jpa:
    show-sql: true
logging:
  level:
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: DEBUG
            StatementCreatorUtils: TRACE
