server:
  port: 8092
  compression:
    enabled: true

spring:
  data:
    rest:
      detection-strategy: annotated
  datasource:
    url: jdbc:postgresql://127.0.0.1:5433/rashod_java_prod
    username: postgres
    password: p123
  jpa:
    generate-ddl: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate
  liquibase:
    changeLog: classpath:/liquibase/db.changelog-master.xml
    drop-first: false

logging:
  level:
    org:
      hibernate:
        type: INFO
        SQL: INFO
app:
#  this is test public key. In production mode ovverride public key use config-server
  security:
    jwt:
      public-key: |
        -----BEGIN PUBLIC KEY-----
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmEJoLD4j2ZyqiiE3Vmv9
        Lr3SAm+Y1HezWQCobsKLuQWFPdEN5Y9haVlzfi3khi6hjn4K0Cg3gSjtlyzdhsUt
        kFQIWktH9f7+6UXiApPHVipgVFcJJ/wl9EIsXVr0Txmh150+3aP3NPDIKWA9KT7/
        jaPwjWH8qgu5Kidrjxi9DJ/3+diEiYyCp8Bi66Lbxk6YymOeoJDH+VeAn3ziSI+w
        G20pEe9HVBzEXm+9LqSI2yURhA3VA50fRBqRd+rRBBp+qlLfGsVBYnenB5MmHD0f
        SLhJeJVf6wSSBA3GxBRu6xPJMf18d3np3gqqwLlqBhlHojoDn4mVlge/rrBljf7K
        NQIDAQAB
        -----END PUBLIC KEY-----
  param:
    operation:
      transferCategory: Перевод
      equalizationCategory: Уравнивание
    dictionaries:
      operationTypes:
        - key: CONSUMPTION
          value: Расход
        - key: INCOME
          value: Доход
        - key: TRANSFER
          value: Перевод
      accountTypes:
        - key: SIMPLE
          value: Простой
        - key: DEBT
          value: Долг
        - key: GOAL
          value: Цель
      currencies:
        - key: RUB
          value: Рубль
        - key: EURO
          value: Евро
        - key: DOLLAR
          value: Доллар
        - key: AURUM
          value: Золото
        - key: ARGENTUM
          value: Серебро
        - key: YANDEX
          value: Акции Яндекс
        - key: ETF_CH
          value: Акции Китайских компаний
        - key: LTC
          value: Lite Coin
        - key: XRP
          value: Ripple
        - key: NMC
          value: Name Coin
        - key: ZEC
          value: ZEC
        - key: XMR
          value: XMR
        - key: VTC
          value: VTC
      accountStatuses:
        - key: ACTIVE
          value: Активен
        - key: INACTIVE
          value: Архивный
      paramGroups:
        - key: COMMON
          value: Общие
        - key: PLAN
          value: План
        - key: DEFAULT_VALUES
          value: Значения по умолчанию
      paramKeys:
        - key: SUM_TO_MONTH
          value: План на текущий месяц
        - key: CREATE_OPERATION_CATEGORY
          value: Категория по умолчанию при создании
        - key: CREATE_OPERATION_ACCOUNT
          value: Счет по умолчанию при создании
management:
  endpoints:
    web:
      exposure:
        include: '*'
