spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5433/rashod_java
    username: postgres
    password: p123
  liquibase:
    drop-first: false
  jpa:
    show-sql: true
server:
  port: 8093
